In [1]:
library(gtools)
library(dplyr)
library(ggplot2)

Warning message:
"package 'gtools' was built under R version 3.6.3"
Attaching package: 'dplyr'

The following objects are masked from 'package:stats':

    filter, lag

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union

Registered S3 methods overwritten by 'ggplot2':
  method         from
  [.quosures     rlang
  c.quosures     rlang
  print.quosures rlang

In [2]:
# load data
inTeams<-read.csv("https://projects.fivethirtyeight.com/soccer-api/club/spi_global_rankings.csv")

In [3]:
# PRE SIMULATION WORK

In [4]:
# Prize dataframe
ranks <- 1:20
prizes <- matrix(ranks, nrow=20, ncol=1, byrow=FALSE)
prizes <- as.data.frame(prizes)
colnames(prizes) <- c('team_rank')
prizes$prize <- c(225,210,200,190,160,150,140,125,123,120,118,115,112,110,108,105,100,52,50,49)

In [5]:
# taking averages
mean.off<-mean(inTeams$off)
mean.def<-mean(inTeams$def)
lmean.off<-mean(log(inTeams$off))
lmean.def<-mean(log(inTeams$def)) 

# subset to premier league
premLeague<-subset(inTeams,league=="Barclays Premier League")
premTeams<-premLeague$name
rownames(premLeague)<-premTeams
df.prem<-premLeague[,c("off","def")]
df.prem

# build parameters
lmean.def<- log(mean(df.prem$def))
lmean.off<- log(mean(df.prem$off))               
df.prem["alpha"]<-log(df.prem["off"])-lmean.def
df.prem["delta"]<-lmean.off-log(df.prem["def"])
alphaList<-df.prem$alpha
deltaList<-df.prem$delta
names(alphaList)<-rownames(df.prem)
names(deltaList)<-rownames(df.prem)

                         off  def
Manchester City          2.90 0.20
Liverpool                2.92 0.25
Chelsea                  2.39 0.29
Arsenal                  2.16 0.46
Tottenham Hotspur        2.36 0.65
Manchester United        2.19 0.67
Aston Villa              1.99 0.63
West Ham United          2.02 0.73
Brighton and Hove Albion 1.85 0.62
Crystal Palace           1.89 0.69
Wolverhampton            1.73 0.61
Southampton              1.94 0.89
Leicester City           2.04 1.00
Brentford                1.80 0.85
Newcastle                1.75 0.82
Burnley                  1.62 0.83
Everton                  1.70 0.93
Leeds United             1.92 1.15
Watford                  1.65 1.08
Norwich City             1.51 1.19

In [6]:
# simulate score line for a match
draw.score<-function(team1,team2){
    c(
        rpois(1,exp(alphaList[team1]-deltaList[team2])),
  rpois(1,exp(alphaList[team2]-deltaList[team1]))
    )
}
draw.score("Liverpool","Arsenal")

[1] 0 1

In [7]:
# All possible matches in a season
allMatches<-permutations(20, 2, v=rownames(df.prem),repeats.allowed=FALSE)
colnames(allMatches)<-c("home","away")

[1] 380

In [8]:
# SIMULATION

In [9]:
SeasonSim <- function(allMatches){
     ScoresMatrix <- matrix(nrow=nrow(allMatches),  ncol=4)
        for (ii in 1:nrow(allMatches)  ) {
         ScoresMatrix[ii,1:2]=allMatches[ii,]
         ScoresMatrix[ii,3:4]= as.numeric(draw.score(allMatches[ii,"home"],allMatches[ii,"away"] ))
        }
        colnames(ScoresMatrix)<-c("home.team","away.team","home.score","away.score")
        ScoresMatrix <- as.data.frame(ScoresMatrix)
        ScoresMatrix$home.score <- as.numeric(ScoresMatrix$home.score)
        ScoresMatrix$away.score <- as.numeric(ScoresMatrix$away.score)  
        
        # PEPARING AGGREGATE STATS DFs
        df.points <- as.data.frame(ScoresMatrix)
        df.points_goalsfor <- as.data.frame(ScoresMatrix)
        df.points_goalsagainst <- as.data.frame(ScoresMatrix)
        name <- rownames(df.prem)
        for (i in 1:20){
            df.points[, name[i]] <- 0
        }
        # ASSIGNING POINTS PER MATCH
        for (i in 1:380){ 
            for (j in 1:20){
                if (df.points[i,1] == name[j]){
                    if (df.points[i,3] > df.points[i,4]){
                        df.points[i,j+4] = 3
                    } else if (df.points[i,3] == df.points[i,4]){
                        df.points[i,j+4] = 1
                    } else if (df.points[i,3] < df.points[i,4]){
                        df.points[i,j+4] = 0
                    } 
                } 
                if (df.points[i,2] == name[j]){
                    if (df.points[i,3] > df.points[i,4]){
                        df.points[i,j+4] = 0
                    } else if (df.points[i,3] == df.points[i,4]){
                        df.points[i,j+4] = 1
                    } else if (df.points[i,3] < df.points[i,4]){
                        df.points[i,j+4] = 3
                    }      
                }
            }   
        } 
        # PREPARING DFs
        for (i in 1:20){
            df.points_goalsfor[, name[i]] <- 0
        }
        for (i in 1:20){
            df.points_goalsagainst[, name[i]] <- 0
        }
    
        # GOALS FOR
        for (i in 1:380){
            for (j in 1:20){
                if (df.points_goalsfor[i,1] == name[j]){ # looking at home team
                    df.points_goalsfor[i,j+4] = df.points_goalsfor[i,3]  # home points go to goals for
                }
                if (df.points_goalsfor[i,2] == name[j]){ # looking at away team
                    df.points_goalsfor[i,j+4] = df.points_goalsfor[i,4] # away points go to goals for
                }
            }
        }
    
        # GOALS AGAINST
        for (i in 1:380){
            for (j in 1:20){
                if (df.points_goalsagainst[i,1] == name[j]){ # looking at home team
                    df.points_goalsagainst[i,j+4] = df.points_goalsagainst[i,4]  # home points go to goals for
                }
                if (df.points_goalsagainst[i,2] == name[j]){ # looking at away team
                    df.points_goalsagainst[i,j+4] = df.points_goalsagainst[i,3] # away points go to goals for
                }
            }
        } 
    
        # AGGREGATING POINTS and GOALS
        points <- df.points[,c(-1,-2,-3,-4)]
        points <- sapply(points, as.numeric)
        points_sum <- as.data.frame(colSums(points))
    
        goalsfor <- df.points_goalsfor[,c(-1,-2,-3,-4)]
        goalsfor <- sapply(goalsfor, as.numeric)
        goalsfor_sum <- as.data.frame(colSums(goalsfor))

        goalsagainst <- df.points_goalsagainst[,c(-1,-2,-3,-4)]
        goalsagainst <- sapply(goalsagainst, as.numeric)
        goalsagainst_sum <- as.data.frame(colSums(goalsagainst))
    
        # MERGE TO ONE DF
        df.teams <- cbind(points_sum, goalsfor_sum, goalsagainst_sum)
        colnames(df.teams)[1] <- 'points'
        colnames(df.teams)[2] <- 'goals_for'
        colnames(df.teams)[3] <- 'goals_against'
        df.teams$team_names <- row.names(df.teams)
    
        # ADD TIE BREAKER VARIABLES
        df.teams <- df.teams %>%
            mutate(net_goals = goals_for - goals_against) %>%
            mutate(tie_breaker = runif(20, 0, 1))
    
        df.teams1 <- df.teams
        df.teams1$team_rank <- rank(desc(df.teams1$points))
        df.teams1$goals_rank <- rank(desc(df.teams1$net_goals))
        df.teams1$goalsfor_rank <- rank(desc(df.teams1$goals_for))
    
        # RANK 
        for (ii in 1:nrow(df.teams1)){
            for (jj in 1:nrow(df.teams1)){
                if (ii != jj & df.teams1[ii,7] == df.teams1[jj,7]){
                    if (df.teams1[ii,8] > df.teams1[jj,8]){ #goals rank
                        df.teams1[ii,7] = df.teams1[ii,7]+0.5
                        df.teams1[jj,7] = df.teams1[jj,7]-0.5
                    } else if (df.teams1[ii,8] == df.teams1[jj,8]){ #goals_for rank
                        if (df.teams1[ii,9] > df.teams1[jj,9]){
                            df.teams1[ii,7] = df.teams1[ii,7]+0.5
                            df.teams1[jj,7] = df.teams1[jj,7]-0.5
                        } else if (df.teams1[ii,9] == df.teams1[jj,9]){                   
                            if (df.teams1[ii,6] > df.teams1[jj,6]){
                            df.teams1[ii,7] = df.teams1[ii,7]+0.5
                            df.teams1[jj,7] = df.teams1[jj,7]-0.5
                            }   
                        }
                    }
                }
            }
        }
        # ASSIGN PRIZE
        df.earnings <- left_join(df.teams1, prizes, by=c("team_rank"))
        df.earnings
    }

In [10]:
# results df
finalcol <- c("points", "goals_for", "goals_against", "team_names", "net_goals", "tie_breaker", "team_rank", "goals_rank", "goalsfor_rank", "prize")
df.final.output <- as.data.frame(matrix(ncol = length(finalcol), nrow=0, dimnames = list(NULL,finalcol)))

# simulations
nsims <- 2

# simulation
for (rep in 1:nsims) {
    df.sim.earnings <- SeasonSim(allMatches)
    df.sim.earnings$sim <- rep
    df.final.output <- rbind(df.final.output, df.sim.earnings)
}
df.final.output

   points goals_for goals_against team_names               net_goals
1  88     120        51           Manchester City           69
2  84      89        49           Liverpool                 40
3  77      93        54           Chelsea                   39
4  56      69        62           Arsenal                    7
5  47      73        68           Tottenham Hotspur          5
6  58      88        72           Manchester United         16
7  55      74        69           Aston Villa                5
8  40      67        83           West Ham United          -16
9  50      71        66           Brighton and Hove Albion   5
10 63      81        69           Crystal Palace            12
11 45      76        81           Wolverhampton             -5
12 53      77        79           Southampton               -2
13 47      80        91           Leicester City           -11
14 46      76        84           Brentford                 -8
15 43      67        75           Newcastle                 -8
16 30      67        94           Burnley                  -27
17 41      69        93           Everton                  -24
18 45      76        96           Leeds United             -20
19 30      64       103           Watford                  -39
20 30      75       113           Norwich City             -38
21 79      94        52           Manchester City           42
22 75      94        60           Liverpool                 34
23 78      89        56           Chelsea                   33
24 72      82        56           Arsenal                   26
25 59      76        71           Tottenham Hotspur          5
26 63      82        71           Manchester United         11
27 58      76        69           Aston Villa                7
28 54      82        77           West Ham United            5
29 42      65        79           Brighton and Hove Albion -14
30 59      79        73           Crystal Palace             6
31 39      65        79           Wolverhampton            -14
32 45      82        83           Southampton               -1
33 51      77        82           Leicester City            -5
34 45      69        70           Brentford                 -1
35 30      68        92           Newcastle                -24
36 49      85        82           Burnley                    3
37 52      79        79           Everton                    0
38 31      75       110           Leeds United             -35
39 38      74        96           Watford                  -22
40 16      58       114           Norwich City             -56
   tie_breaker team_rank goals_rank goalsfor_rank prize sim
1  0.75205140   1.0       1.0        1.0          225   1
2  0.38089262   2.0       2.0        3.0          210   1
3  0.39511585   3.0       3.0        2.0          200   1
4  0.34671561   6.0       6.0       15.5          150   1
5  0.76222547  10.0       8.0       13.0          120   1
6  0.07538633   5.0       4.0        4.0          160   1
7  0.29108122   7.0       8.0       12.0          140   1
8  0.49777422  17.0      15.0       18.0          100   1
9  0.03697351   9.0       8.0       14.0          123   1
10 0.97527585   4.0       5.0        5.0          190   1
11 0.71875909  13.0      11.0        9.0          112   1
12 0.20667795   8.0      10.0        7.0          125   1
13 0.74302140  11.0      14.0        6.0          118   1
14 0.29065833  12.0      12.5        9.0          115   1
15 0.00343650  15.0      12.5       18.0          108   1
16 0.12620809  18.5      18.0       18.0           NA   1
17 0.43419487  16.0      17.0       15.5          105   1
18 0.73888787  14.0      16.0        9.0          110   1
19 0.18443126  19.5      20.0       20.0           NA   1
20 0.44771696  19.0      19.0       11.0           50   1
21 0.78764360   1.0       1.0        1.5          225   2
22 0.65092359   3.0       2.0        1.5          200   2
23 0.30655571   2.0       3.0        3.0          210   2
24 0.67719649   4.0       4.0        6.5          190   2
25 0.66254445   7.0       8.5       12.5          140   2
26 0.99972834   5.0       5.0        6.5          160   2
27 0.28401389   8.0       6.0       12.5          125   2
28 0.47740069   9.0       8.5        6.5          123   2
29 0.86332663  15.0      15.5       18.5          108   2
30 0.37020841   6.0       7.0        9.5          150   2
31 0.58338275  16.0      15.5       18.5          105   2
32 0.47982382  13.0      12.5        6.5          112   2
33 0.63109993  11.0      14.0       11.0          118   2
34 0.35210135  14.0      12.5       16.0          110   2
35 0.24660598  19.0      18.0       17.0           50   2
36 0.87454953  12.0      10.0        4.0          115   2
37 0.01972110  10.0      11.0        9.5          120   2
38 0.12534712  18.0      19.0       14.0           52   2
39 0.09987891  17.0      17.0       15.0          100   2
40 0.61942606  20.0      20.0       20.0           49   2